//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Информационная_система_v2
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceMessage
    {
        public int Id { get; set; }
        public string Text { get; set; }
        public System.DateTime Date { get; set; }
        public int SenderCode { get; set; }
        public int RecipientCode { get; set; }
        public bool Checked { get; set; }
        public string Title { get; set; }
    
        public virtual Administrator Administrator { get; set; }
        public virtual Device Device { get; set; }

        public string GetChecked()
        {
            if (Checked)
                return "Прочитано";
            else return "Не прочитано";
        }

    }
}
