//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Информационная_система_v2
{
    using System;
    using System.Collections.Generic;
    
    public partial class HealthStatus
    {
        public string Status { get; set; }
        public int Number { get; set; }
        public System.DateTime CreatingTime { get; set; }
        public int OwnerCode { get; set; }
    
        public virtual Patient Patient { get; set; }

        public static string[] SymptomsNames =
        {
            "Недомогание", "Головокружение", "Повышенное артериальное давление", "Пониженное артериальное давление",
            "Жар", "Головная боль", "Бессонница", "Тошнота", "Усталость", "Сухость во рту", "Прибавление веса",
            "Потеря веса", "Слабость", "Жажда"
        };

        public static string GetHealthStatus(bool[] symptoms)
        {
            string status = string.Empty;
            int symptomNumber = 0;

            foreach (bool symptom in symptoms)
            {
                if (symptom)
                    status += SymptomsNames[symptomNumber] + ", ";

                symptomNumber++;
            }

            if (status == string.Empty)
                status = "Симптомы не отмечены";
            else
            {
                status = status.Trim();
                status = status.Remove(status.Length - 1, 1);
            }

            return status;
        }

        public static bool[] GetBoolArray(string status)
        {
            bool[] symptoms = new bool[14];

            if (status != "Симптомы не отмечены")
            {
                int symptomNumber = 0;


                foreach (string symptom in SymptomsNames)
                {
                    if (status.IndexOf(symptom) != -1)
                        symptoms[symptomNumber] = true;

                    symptomNumber++;
                }
            }
            return symptoms;
        }
    }
}
