//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Информационная_система_v2
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeasuredData: IComparable<MeasuredData>
    {
        public int DeviceCode { get; set; }
        public long Number { get; set; }
        public System.DateTime CreatingTime { get; set; }
        public int OwnerCode { get; set; }
        public string Value { get; set; }
    
        public virtual Patient Patient { get; set; }

        public int CompareTo(MeasuredData data)
        {
            if (this.Number > data.Number)
                return 1;
            else if (this.Number == data.Number)
                return 0;
            else
                return -1;
        }
    }
}
